name: Angular CI Pipeline

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npx ng test --no-watch --browsers=ChromeHeadless

      - name: Build application
        run: npx ng build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: production-build
          path: dist/sjp-locacoes-frontend/
