# .github/workflows/main.yml

name: Angular CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npx ng test --no-watch --browsers=ChromeHeadless
      - run: npx ng build
      - uses: actions/upload-artifact@v4
        with:
          name: production-build
          # AQUI ESTÁ A MUDANÇA: Pegamos o CONTEÚDO da pasta browser
          path: dist/sjp-locacoes-frontend/browser/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: production-build
      - uses: nwtgck/actions-netlify@v3.0
        with:
          # Agora '.' está correto, pois o artefato não tem mais a pasta extra
          publish-dir: '.'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}